<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
      <PackageReference Include="FastReport.Data.MySql" Version="2025.2.4" />
      <PackageReference Include="FastReport.OpenSource" Version="2025.2.0" />
      <PackageReference Include="FastReport.OpenSource.Export.PdfSimple" Version="2025.2.0" />
      <PackageReference Include="Microsoft.Reporting.WinForms.v11" Version="1.0.0" />
      <PackageReference Include="MySql.Data" Version="9.3.0" />
      <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="9.0.0" />
    </ItemGroup>

</Project>
