package ventanas;
import app.JStatusBar;
import config.AppConfig;
import util.AdminIFrame;
/**
 * @author Ferz
 */
public class MainWindow extends javax.swing.JFrame {

    
    private static IProveedores vntProveedores = null;
    private static ISimpleModelo vntModeloMarcaClase = null;
    private static IUsuario vntUsuario = null;
    private static IProducto vntProducto = null;
    private static ICompra vntCompra = null;
    private static IProveedores vntProveedor = null;
    private static ISimpleModelo vntModelo = null;
    public MainWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
        System.out.println(AppConfig.getUsuario().getNombre()+" - "+AppConfig.getUsuario().getApellidos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dp = new javax.swing.JDesktopPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new JStatusBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Ventas");
        setExtendedState(MAXIMIZED_BOTH);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jInternalFrame1.setTitle("Nota: Sistema de Ventas");
        jInternalFrame1.setVisible(true);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(50, 50));

        jEditorPane1.setEditable(false);
        jEditorPane1.setContentType("text/html"); // NOI18N
        jEditorPane1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jEditorPane1.setText("<html>\r\n  <head>\r\n\r\n  </head>\r\n  <body>\r\n    <p style=\"margin-top: 0\">\r\n<h3 style=\"margin-top: 0px; text-align: center;\"><img src=\"https://pbs.twimg.com/profile_images/869029836521709568/h9EReds8_400x400.jpg\" alt=\"\" width=\"200\" height=\"200\" /></h3>\n<h3 style=\"margin-top: 0px; text-align: center;\">Este Software es modificado por <span style=\"color: #ff0000;\"><strong>C&oacute;digo Lite</strong></span> el codigo original fue descargado de internet y modificado y se presenta como un demostrativo. su fin es educacional.</h3>\n<h3 style=\"margin-top: 0px; text-align: center;\">La persona que obtiene este software puede modificar, adaptar o cambiar siempre y cuando incluya el nombre del autor.</h3>\n<ul>\n<li>\n<h3>Sitio web: <a href=\"http:/codigolite.com\">https://codigolite.com</a></h3>\n</li>\n<li>\n<h3>Pagina Facebook : <a href=\"http://www.facebook.com/CodigoLite\">http://www.facebook.com/codigolite</a></h3>\n</li>\n<li>\n<h3>Canal Youtube : <a href=\"https://www.youtube.com/channel/UCE1829XGWYnlJuS75jqBA8A\">https://www.youtube.com/channel/UCE1829XGWYnlJuS75jqBA8A</a></h3>\n</li>\n<li>\n<h3>Twitter : <a href=\"https://twitter.com/codigolite\">https://twitter.com/codigolite</a></h3>\n</li>\n<li>\n<h3>Google+ : <a href=\"https://plus.google.com/107174270365160938863\">https://plus.google.com/107174270365160938863</a></h3>\n</li>\n</ul>\n    </p>\r\n  </body>\r\n</html>\r\n");
        jEditorPane1.setPreferredSize(new java.awt.Dimension(1137, 525));
        jScrollPane1.setViewportView(jEditorPane1);

        jInternalFrame1.getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        dp.add(jInternalFrame1);
        jInternalFrame1.setBounds(10, 10, 680, 600);
        jInternalFrame1.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(dp);

        jPanel1.setPreferredSize(new java.awt.Dimension(549, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 841, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/predeterminado.png"))); // NOI18N
        jMenu1.setText("Archivo");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/eliminar.png"))); // NOI18N
        jMenuItem6.setText("Salir");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/user_blue_32.png"))); // NOI18N
        jMenu3.setText("Producto");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/agregar.png"))); // NOI18N
        jMenuItem3.setText("Registrar Producto");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tick.png"))); // NOI18N
        jMenuItem4.setText("Compra");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search32.png"))); // NOI18N
        jMenu2.setText("Mantenimiento");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/user_blue_32.png"))); // NOI18N
        jMenuItem1.setText("Registrar Usuario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/agregar_over.png"))); // NOI18N
        jMenuItem2.setText("Registrar Proveedores");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/agregar.png"))); // NOI18N
        jMenuItem5.setText("Registrar Clase - Marcas - Modelos");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       System.out.println("******");
       if(vntUsuario== null)
       {
           vntUsuario = new IUsuario(); 
       }
       AdminIFrame.mostrarVentanaFactura(dp, vntUsuario); 
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      System.out.println("******---");
       if(vntProveedores == null)
       {
           vntProveedores = new IProveedores(); 
       }
       AdminIFrame.mostrarVentanaFactura(dp, vntProveedores); 
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if(vntProducto== null)
       {
           vntProducto = new IProducto(); 
       }
       AdminIFrame.mostrarVentanaFactura(dp, vntProducto);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if(vntCompra== null)
       {
           vntCompra = new ICompra(); 
       }
       AdminIFrame.mostrarVentanaFactura(dp, vntCompra);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
         if(vntModeloMarcaClase == null)
       {
           vntModeloMarcaClase = new ISimpleModelo(); 
       }
       AdminIFrame.mostrarVentanaFactura(dp, vntModeloMarcaClase); 
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dp;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
